// app/components/footer.tsx
function ArrowIcon() {
  return (
    <svg
      width="12"
      height="12"
      viewBox="0 0 12 12"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M2.07102 11.3494L0.963068 10.2415L9.2017 1.98864H2.83807L2.85227 0.454545H11.8438V9.46023H10.2955L10.3097 3.09659L2.07102 11.3494Z"
        fill="currentColor"
      />
    </svg>
  );
}

export default function Footer() {
  return (
    <footer className="mb-16">
      <ul className="font-sm mt-8 flex flex-col space-x-0 space-y-2 text-neutral-600 md:flex-row md:space-x-4 md:space-y-0 dark:text-neutral-300">
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://bitsbythebyte.pub/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">blog</p>
          </a>
        </li>
        {/* <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://bitsbythebyte.com/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">cyberspace</p>
          </a>
        </li>
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://bitsbythebyte.net/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">api</p>
          </a>
        </li> */}
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://x.com/heyitsjoealongi/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">x</p>
          </a>
        </li>
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://github.com/heyitsjoealongi/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">github</p>
          </a>
        </li>
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://www.linkedin.com/in/heyitsjoealongi/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">linkedin</p>
          </a>
        </li>
      </ul>
      <p className="mt-8 text-neutral-600 dark:text-neutral-300">
        © {new Date().getFullYear()} Joe Alongi
      </p>
    </footer>
  );
}

// components/footer.vue
<template>
  <footer>
    <ul
      class="heyitsjoealongi-theme-footer flex flex-col md:flex-row flex-auto my-3"
    >
      <li class="flex items-center">
        <a
          class="transition-all"
          rel="noopener noreferrer"
          target="_blank"
          href="https://blog.heyitsjoealongi.com/"
        >
          <p
            class="mb-3 md:mb-0 md:mr-6 text-base antialiased font-black text-left"
          >
            blog
          </p>
        </a>
      </li>
      <li class="flex items-center">
        <a
          class="transition-all"
          rel="noopener noreferrer"
          target="_blank"
          href="https://x.com/heyitsjoealongi/"
        >
          <p
            class="mb-3 md:mb-0 md:mr-6 text-base antialiased font-black text-left"
          >
            x
          </p>
        </a>
      </li>
      <li class="flex items-center">
        <a
          class="transition-all"
          rel="noopener noreferrer"
          target="_blank"
          href="https://github.com/heyitsjoealongi/"
        >
          <p
            class="mb-3 md:mb-0 md:mr-6 text-base antialiased font-black text-left"
          >
            github
          </p>
        </a>
      </li>
      <li class="flex items-center">
        <a
          class="transition-all"
          rel="noopener noreferrer"
          target="_blank"
          href="https://www.instagram.com/heyitsjoealongi/"
        >
          <p
            class="mb-3 md:mb-0 md:mr-6 text-base antialiased font-black text-left"
          >
            instagram
          </p>
        </a>
      </li>
      <li class="flex items-center">
        <a
          class="transition-all"
          rel="noopener noreferrer"
          target="_blank"
          href="https://www.linkedin.com/in/heyitsjoealongi/"
        >
          <p
            class="mb-3 md:mb-0 md:mr-6 text-base antialiased font-black text-left"
          >
            linkedin
          </p>
        </a>
      </li>
      <li class="flex items-center">
        <a
          class="transition-all"
          rel="noopener noreferrer"
          target="_blank"
          href="https://www.youtube.com/@heyitsjoealongi/"
        >
          <p
            class="mb-3 md:mb-0 md:mr-6 text-base antialiased font-black text-left"
          >
            youtube
          </p>
        </a>
      </li>
    </ul>
  </footer>
</template>

<script lang="ts" setup></script>

<style></style>
